module.exports = {
  darkMode: "class",
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#c3e8ff",
        "surface-container-highest": "#343538",
        "secondary-container": "#094c67",
        "surface-tint": "#9ccaff",
        "on-surface-variant": "#c1c7d1",
        "primary-container": "#085c96",
        "surface-container": "#1e2022",
        "inverse-primary": "#16629c",
        "surface-container-lowest": "#0d0e11",
        "primary-fixed-dim": "#9ccaff",
        "on-tertiary-container": "#c0d1e6",
        "on-primary": "#003256",
        "surface-dim": "#121316",
        "tertiary-container": "#4a5a6b",
        "outline": "#8b919b",
        "on-background": "#e3e2e5",
        "on-tertiary-fixed-variant": "#384859",
        "surface-variant": "#343538",
        "outline-variant": "#414750",
        "secondary-fixed-dim": "#98cded",
        "on-primary-container": "#aed3ff",
        "surface-bright": "#38393c",
        "inverse-on-surface": "#2f3033",
        "primary": "#9ccaff",
        "tertiary": "#b8c8dc",
        "secondary": "#98cded",
        "on-secondary-fixed-variant": "#094c67",
        "on-tertiary": "#223242",
        "tertiary-fixed-dim": "#b8c8dc",
        "on-secondary-container": "#87bcda",
        "primary-fixed": "#d0e4ff",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#00497a",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#001e2c",
        "on-surface": "#e3e2e5",
        "on-secondary": "#003549",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#292a2d",
        "inverse-surface": "#e3e2e5",
        "background": "#121316",
        "surface": "#121316",
        "on-tertiary-fixed": "#0c1d2c",
        "tertiary-fixed": "#d3e4f9",
        "on-primary-fixed": "#001d35",
        "surface-container-low": "#1a1c1e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "3xl": "4px"
      },
      spacing: {
        "stack-lg": "48px",
        "margin-desktop": "64px",
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1200px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-md": ["Libre Caslon Text", "sans-serif"],
        "headline-lg": ["Libre Caslon Text", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Libre Caslon Text", "sans-serif"],
        "display-lg": ["Libre Caslon Text", "sans-serif"],
        "japanese": ["Shippori Mincho", "serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "hero-jp": ["8vw", { lineHeight: "1.2", fontWeight: "400" }],
        "hero-jp-mobile": ["15vw", { lineHeight: "1.2", fontWeight: "400" }]
      }
    }
  }
}